spring:
  profiles:
    default: dev
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
  mvc:
    path match:
      matching-strategy: ant_path_matcher

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSSz,Asia/Seoul